name: Autopep8

on:
  push:
    branches: [ "main" ]
jobs:
  static_analytic_tools:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.x'

        - name: install autopep8
          run: |
            pip install autopep8
        
        - name: run autopep8 in check mode to ensure PEP 8 complaince 
          run: |
            find . -type f -name "*.py" ! -path '*/migrations/*' -exec autopep8 --exit-code --aggressive --aggressive --diff '{}' \;